# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# Baseurl = name of github repository linked to libertarianinstitute account
#
#
projname: Obrana řidičů
projgoal: >
        Projekt Obrana řidičů poskytne řidičům efektivní obranu proti šikaně v rámci zákonných postupů. 
muzetesetesitna: >
        <ul>
        <li>užitečné rady v nejrůznějších situacích, které vás za volantem mohou potkat;</li>
        <li>webovou a mobilní aplikaci Obrana řidičů;</li>
        <li>tištěnou příručku.</li>
        </ul>
title: Libertariani.cz - template
email: michal.kurz@libertariani.cz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nastraneridicu.cz" # the base hostname & protocol for your site
github_username:  libertarianinstitute

# Build settings
markdown: kramdown
